server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: CONFIG-SERVER

  devtools:
    livereload:
      port: 35733

  cloud:
    config:
      server:
        git:
          uri: https://github.com/005Dikshant/SpringBootRepo
          clone-on-start: true