server:
  port: 8081

spring:

  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: dikshant
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  config:
    import: optional:configserver:http://localhost:8085
