server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: dikshant
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  devtools:
    livereload:
      port: 35731